NoiseSFXPointersLo:
	dl NoiseDrumData_ClosedHihat
	dl NoiseDrumData_UpperSnare
	dl NoiseDrumData_OpenHihat
	dl NoiseDrumData_Kick
	dl NoiseDrumData_Snare
	dl NoiseDrumData_DoubleSnare
	dl NoiseDrumData_OWClosedHihat
	dl NoiseDrumData_OWOpenHihat
	dl NoiseDrumData_OWKick
	dl NoiseDrumData_OWSnare
	dl NoiseDrumData_StarSnare
	dl NoiseSFX_Whale
	dl NoiseSFX_Rocket
	dl NoiseSFX_POW
	dl NoiseSFX_Door
	dl NoiseSFX_Bomb
	dl NoiseSFX_Fireball
	dl NoiseSFX_WartBubble
	dl NoiseSFX_WartSmokePuff
	dl NoiseSFX_DrumRoll

NoiseSFXPointersHi:
	dh NoiseDrumData_ClosedHihat
	dh NoiseDrumData_UpperSnare
	dh NoiseDrumData_OpenHihat
	dh NoiseDrumData_Kick
	dh NoiseDrumData_Snare
	dh NoiseDrumData_DoubleSnare
	dh NoiseDrumData_OWClosedHihat
	dh NoiseDrumData_OWOpenHihat
	dh NoiseDrumData_OWKick
	dh NoiseDrumData_OWSnare
	dh NoiseDrumData_StarSnare
	dh NoiseSFX_Whale
	dh NoiseSFX_Rocket
	dh NoiseSFX_POW
	dh NoiseSFX_Door
	dh NoiseSFX_Bomb
	dh NoiseSFX_Fireball
	dh NoiseSFX_WartBubble
	dh NoiseSFX_WartSmokePuff
	dh NoiseSFX_DrumRoll
